# Generated by Django 5.2.12 on 2026-06-28 22:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_delete_clientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.CreateModel(
            name='EmployeeMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('messageType', models.CharField(choices=[('ACTIVATION', 'Activación'), ('CONFIRMATION', 'Confirmación'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PASSWORD_RESET', 'Restablecimiento de contraseña'), ('PASSWORD_RESET_CONFIRM', 'Confirmación de restablecimiento de contraseña')], max_length=50, verbose_name='tipo de mensaje')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('employee_name', models.CharField(blank=True, max_length=255, verbose_name='nombre del empleado')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_messages', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'mensaje de empleado',
                'verbose_name_plural': 'mensajes de empleados',
                'db_table': '"accounts"."employee_messages"',
                'ordering': ['-created_at'],
            },
        ),
    ]
