# Generated by Django 5.2.12 on 2026-06-28 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_phone_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemessages',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_messages', to=settings.AUTH_USER_MODEL, verbose_name='empleado'),
        ),
        migrations.CreateModel(
            name='AdminMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('messageType', models.CharField(choices=[('ACTIVATION', 'Activación'), ('CONFIRMATION', 'Confirmación'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PASSWORD_RESET', 'Restablecimiento de contraseña'), ('PASSWORD_RESET_CONFIRM', 'Confirmación de restablecimiento de contraseña')], max_length=50, verbose_name='tipo de mensaje')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('admin_name', models.CharField(blank=True, max_length=255, verbose_name='nombre del admin')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'mensaje de admin',
                'verbose_name_plural': 'mensajes de admins',
                'db_table': '"accounts"."admin_messages"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('messageType', models.CharField(choices=[('ACTIVATION', 'Activación'), ('CONFIRMATION', 'Confirmación'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('PASSWORD_RESET', 'Restablecimiento de contraseña'), ('PASSWORD_RESET_CONFIRM', 'Confirmación de restablecimiento de contraseña')], max_length=50, verbose_name='tipo de mensaje')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='nombre del cliente')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'mensaje de cliente',
                'verbose_name_plural': 'mensajes de clientes',
                'db_table': '"accounts"."client_messages"',
                'ordering': ['-created_at'],
            },
        ),
    ]
