# Generated by Django 5.2.12 on 2026-06-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_employeemessages_employee_adminmessages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessages',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('SMS', 'SMS')], default='EMAIL', max_length=5, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='clientmessages',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('SMS', 'SMS')], default='EMAIL', max_length=5, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='employeemessages',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('SMS', 'SMS')], default='SMS', max_length=5, verbose_name='canal'),
        ),
    ]
