# Generated by Django 5.2.12 on 2026-06-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminmessages_channel_clientmessages_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessages',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='mensaje de error'),
        ),
        migrations.AddField(
            model_name='adminmessages',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Enviado'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=10, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='clientmessages',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='mensaje de error'),
        ),
        migrations.AddField(
            model_name='clientmessages',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Enviado'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=10, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='employeemessages',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='mensaje de error'),
        ),
        migrations.AddField(
            model_name='employeemessages',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Enviado'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=10, verbose_name='estado'),
        ),
    ]
