# Generated by Django 5.2.12 on 2026-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phone_number_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='clientmessages',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono'),
        ),
    ]
