# Generated by Django 5.2.12 on 2026-06-29 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message_phone_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessages',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='clientmessages',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_messages', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='employeemessages',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_messages', to=settings.AUTH_USER_MODEL, verbose_name='empleado'),
        ),
    ]
