services:
  # Django backend app
  sc_auth:
    container_name: sc_auth
    build: .
    command: uvicorn safe_and_clean_auth.asgi:application --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      sc_db_auth:
        condition: service_healthy
      sc_redis_auth:
        condition: service_started

  # Celery worker
  sc_auth_celery_worker:
    container_name: sc_auth_celery_worker
    build: .
    command: celery -A safe_and_clean_auth worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      sc_db_auth:
        condition: service_healthy
      sc_redis_auth:
        condition: service_started

  # Celery beat
  sc_auth_celery_beat:
    container_name: sc_auth_celery_beat
    build: .
    command: celery -A safe_and_clean_auth beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      sc_db_auth:
        condition: service_healthy
      sc_redis_auth:
        condition: service_started

  # Redis
  sc_redis_auth:
    image: redis
    container_name: sc_redis_auth
    ports:
      - "6380:6379"

  # Database
  sc_db_auth:
    image: postgres:18
    container_name: sc_db_auth
    restart: always
    environment:
      POSTGRES_DB: sc_db_auth
      POSTGRES_USER: sc_user_auth
      POSTGRES_PASSWORD: Db@dm1n_sc_auth
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sc_user_auth -d sc_db_auth"]
      interval: 5s
      timeout: 5s
      retries: 10
